version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: zope-interface
    versions:
    - 5.2.0
    - 5.3.0
  - dependency-name: pyramid
    versions:
    - 1.10.5
    - 1.10.7
  - dependency-name: cornice
    versions:
    - 5.0.3
    - 5.1.0
  - dependency-name: iso8601
    versions:
    - 0.1.13
