language: python
python: 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8

install:
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

script:
  - tox -e $TOX_ENV

after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls

matrix:
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.6
      env:
        - TOX_ENV=py36
