language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
install:
  - pip install -e .[test]
  - pip install pytest
  - pip install coveralls
  - pip install flex

script: py.test cornice_swagger
after_success:
    coveralls --verbose
