on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Unit Testing
jobs:
  chore:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toxenv: [py36, py37, py38, py39, flake8]
        include:
          - toxenv: py36
            python-version: "3.6"
          - toxenv: py37
            python-version: "3.7"
          - toxenv: py38
            python-version: "3.8"
          - toxenv: flake8
            python-version: "3.8"
          - toxenv: py39
            python-version: "3.9"

    steps:
      - uses: actions/checkout@v2
        with:
          # Fetch the latest commit, only
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install virtualenv
        run: |
          pip install virtualenv
          virtualenv --python=python3 .venv

      - name: Print environment
        run: |
          source .venv/bin/activate
          python --version
          pip --version

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          pip install tox
          pip install -r requirements.txt
          pip install -r dev-requirements.txt

      - name: Tox
        run: |
          source .venv/bin/activate
          tox -e ${{ matrix.toxenv }}

      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        if: matrix.toxenv == 'py38'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
